{
 "title": "request info",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ceil(http_requests_total{job=\"fastapi\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"fastapi\"}) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, endpoint) (http_request_duration_seconds_bucket{job=\"fastapi\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}